core/apps/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.render_account_page, name='home-page'),
]

core/apps/blog/urls.py
from django.urls import path

from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.render_blog_page, name='home-page'),
]

core/apps/categories/urls.py
from django.urls import path

from . import views

app_name = 'categories'

urlpatterns = [
    path('', views.render_shop_page, name='shop-page'),
    path('<slug:category_slug>/', views.render_category_page, name='category-products'),
]

core/apps/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.render_home_page, name='home-page'),
    path('contacts/', views.render_contact_page, name='contact-page'),
    path('about/', views.render_about_page, name='about-page'),
    path('faqs/', views.render_faqs_page, name='faqs-page'),
]

core/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.apps.main.urls')),
    path('categories/', include('core.apps.categories.urls')),
    path('accounts/', include('core.apps.accounts.urls')),
    path('blog/', include('core.apps.blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/apps/accounts/models.py
from django.db import models

# Create your models here.

core/apps/blog/models.py
from django.db import models

from core.apps.common.models import BaseModel


class BlogPostTag(BaseModel):
    name = models.CharField(max_length=100, unique=True, verbose_name="Название тега")

    class Meta(BaseModel.Meta):
        verbose_name = "Тег поста"
        verbose_name_plural = "Теги постов"
        ordering = ["-created_at"]

    def __str__(self):
        return self.name


class BlogPost(BaseModel):
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    short_description = models.TextField(verbose_name="Краткое описание")
    content = models.TextField(verbose_name="Контент")
    preview = models.ImageField(
        upload_to="blog/previews/",
        null=True,
        blank=True,
        verbose_name="Заставка",
    )
    tags = models.ManyToManyField(
        BlogPostTag,
        related_name="blog_posts",
        blank=True,
        verbose_name="Теги",
    )

    class Meta(BaseModel.Meta):
        verbose_name = "Пост блога"
        verbose_name_plural = "Посты блога"
        ordering = ["-created_at"]

    def __str__(self):
        return self.title

core/apps/categories/models.py
from django.db import models
from django.urls import reverse

from core.apps.categories.schemas import CategorySchema
from core.apps.common.models import BaseModel


class Category(BaseModel):
    name = models.CharField(verbose_name='Название', max_length=150, unique=True)
    slug = models.SlugField(verbose_name='Короткая ссылка', help_text='Данное поле заполнять не нужно')
    icon = models.ImageField(verbose_name='Иконка', upload_to='categories/icons/', null=True, blank=True)

    def get_absolute_url(self):
        return reverse("categories:category-products", kwargs={"category_slug": self.slug})

    def to_entity(self) -> CategorySchema:
        return CategorySchema(
            id=self.id,
            name=self.name,
            slug=self.slug,
            icon=self.icon.url if self.icon else None
        )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

core/apps/common/models.py
import uuid

from django.db import models


class BaseModel(models.Model):
    """
    An abstract base model that provides common fields for all models.
    """

    id = models.UUIDField(
        primary_key=True, editable=False, verbose_name="ID", default=uuid.uuid4
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created At")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated At")

    class Meta:
        abstract = True
        ordering = ["-created_at"]

core/apps/main/models.py
from django.db import models

from core.apps.common.models import BaseModel


class Banner(BaseModel):
    image = models.ImageField(verbose_name='Фото', upload_to='banners/')
    short_description = models.CharField(verbose_name='Краткое описание', max_length=100)
    description = models.CharField(verbose_name='Текст', max_length=150)
    category = models.ForeignKey("categories.Category", on_delete=models.SET_NULL, verbose_name='Категория',
                                 null=True)

    def __str__(self):
        return self.description

    def get_image(self):
        if not self.image:
            return ""
        return self.image.url

    class Meta:
        verbose_name = 'Банер'
        verbose_name_plural = 'Банеры'

core/apps/products/models.py
from django.db import models

from core.apps.common.models import BaseModel


class ProductSizeChoices(models.TextChoices):
    XL = 'XL', 'XL'
    L = 'L', 'L'
    M = 'M', 'M'
    S = 'S', 'S'


class ProductColorChoices(models.TextChoices):
    RED = 'RED', 'RED'
    BLUE = 'BLUE', 'BLUE'
    BLACK = 'BLACK', 'BLACK'
    GRAY = 'GRAY', 'GRAY'


class ProductBrand(BaseModel):
    name = models.CharField(verbose_name='название', max_length=150)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Бренд продукта'
        verbose_name_plural = 'Бренды продуктов'


class ProductTag(BaseModel):
    name = models.CharField(verbose_name='Название', max_length=150)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег продукта'
        verbose_name_plural = 'Теги продуктов'


class Product(BaseModel):
    name = models.CharField(verbose_name='Название', max_length=150)
    slug = models.SlugField(verbose_name='Короткая ссылка', help_text='Данное поле заполнять не нужно')
    preview = models.ImageField(verbose_name='Превью', upload_to='products/previews/', null=True, blank=True)
    price = models.DecimalField(verbose_name='Цена', max_digits=10, decimal_places=2)
    description = models.TextField(verbose_name='описание', null=True, blank=True)
    additional = models.TextField(verbose_name='Дополнительная информация', null=True, blank=True)
    quantity = models.IntegerField(verbose_name='Количество', default=5)
    sku = models.CharField(verbose_name='SKU', max_length=150, unique=True)
    category = models.ManyToManyField("categories.Category", related_name="products",
                                      verbose_name='Категория')
    size = models.CharField(verbose_name='Размер', choices=ProductSizeChoices.choices, max_length=2, null=True,
                            blank=True)
    color = models.CharField(verbose_name='Цвет', choices=ProductColorChoices.choices, max_length=10, null=True,
                             blank=True)
    brand = models.ForeignKey(ProductBrand, verbose_name='Бренд', on_delete=models.CASCADE, related_name='products')
    tags = models.ManyToManyField(ProductTag, related_name='tags', verbose_name='Теги')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class ProductImage(BaseModel):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images', verbose_name='Продукт')
    image = models.ImageField(verbose_name='Фото', upload_to='products/images/')

    def __str__(self):
        return self.product.name

    class Meta:
        verbose_name = 'Фото продукта'
        verbose_name_plural = 'Фотки продуктов'

core/apps/accounts/views.py
from django.shortcuts import render

from django.http import HttpRequest, HttpResponse


def render_account_page(request: HttpRequest) -> HttpResponse:
    return render(request, 'apps/account/index.html')

core/apps/blog/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from .models import BlogPost


def render_blog_page(request: HttpRequest) -> HttpResponse:
    posts = BlogPost.objects.all()
    context = {
        'posts': posts,
    }
    return render(request, 'apps/blog/index.html', context)

core/apps/categories/views.py
from django.http import HttpRequest
from django.shortcuts import HttpResponse, render


def render_shop_page(request: HttpRequest) -> HttpResponse:
    return render(request, "apps/categories/index.html")


def render_category_page(request: HttpRequest, category_slug: str):
    return HttpResponse(f'category with slug: {category_slug}')

core/apps/main/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from .models import Banner


def render_home_page(request: HttpRequest) -> HttpResponse:
    banners = Banner.objects.all()
    context = {
        'banners': banners,
    }
    return render(request, "apps/main/index.html", context)


def render_contact_page(request: HttpRequest) -> HttpResponse:
    return render(request, "apps/main/contact.html")


def render_about_page(request: HttpRequest) -> HttpResponse:
    return render(request, 'apps/main/about.html')


def render_faqs_page(request: HttpRequest) -> HttpResponse:
    return render(request, 'apps/main/faqs.html')

core/apps/products/views.py
from django.shortcuts import render

# Create your views here.

core/templates/components/base/_footer.html
{% load static %}

<footer id="footer" class="my-5">
    <div class="container py-5 my-5">
        <div class="row">
            <div class="col-md-3">
                <div class="footer-menu">
                    <img src="{% static 'images/logo.png' %}" alt="logo">
                    <p class="blog-paragraph fs-6 mt-3">Subscribe to our newsletter to get updates about our grand
                        offers.</p>
                    <div class="social-links">
                        <ul class="d-flex list-unstyled gap-2">
                            <li class="social">
                                <a href="#">
                                    <iconify-icon class="social-icon" icon="ri:facebook-fill"></iconify-icon>
                                </a>
                            </li>
                            <li class="social">
                                <a href="#">
                                    <iconify-icon class="social-icon" icon="ri:twitter-fill"></iconify-icon>
                                </a>
                            </li>
                            <li class="social">
                                <a href="#">
                                    <iconify-icon class="social-icon" icon="ri:pinterest-fill"></iconify-icon>
                                </a>
                            </li>
                            <li class="social">
                                <a href="#">
                                    <iconify-icon class="social-icon" icon="ri:instagram-fill"></iconify-icon>
                                </a>
                            </li>
                            <li class="social">
                                <a href="#">
                                    <iconify-icon class="social-icon" icon="ri:youtube-fill"></iconify-icon>
                                </a>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="footer-menu">
                    <h3>Quick Links</h3>
                    <ul class="menu-list list-unstyled">
                        <li class="menu-item">
                            <a href="{% url 'main:home-page' %}" class="nav-link">Home</a>
                        </li>
                        <li class="menu-item">
                            <a href="{% url 'main:about-page' %}" class="nav-link">About us</a>
                        </li>
                        <li class="menu-item">
                            <a href="{% url 'main:contact-page' %}" class="nav-link">Conatct Us</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3">
                <div class="footer-menu">
                    <h3>Help Center</h3>
                        <ul class="menu-list list-unstyled">
                            <li class="menu-item">
                                <a href="{% url 'main:faqs-page' %}" class="nav-link">FAQs</a>
                            </li>
                            <li class="menu-item">
                                <a href="#" class="nav-link">Payment</a>
                            </li>
                            <li class="menu-item">
                                <a href="#" class="nav-link">Returns & Refunds</a>
                            </li>
                            <li class="menu-item">
                                <a href="#" class="nav-link">Checkout</a>
                            </li>
                            <li class="menu-item">
                                <a href="#" class="nav-link">Delivery Information</a>
                            </li>
                        </ul>
                </div>
            </div>
            <div class="col-md-3">
                <div>
                    <h3>Our Newsletter</h3>
                    <p class="blog-paragraph fs-6">Subscribe to our newsletter to get updates about our grand offers.
                    </p>
                    <div class="search-bar border rounded-pill border-dark-subtle px-2">
                        <form class="text-center d-flex align-items-center" action="" method="post">
                            <input type="text" class="form-control border-0 bg-transparent"
                                placeholder="Enter your email here" />
                            <iconify-icon class="send-icon" icon="tabler:location-filled"></iconify-icon>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</footer>

core/templates/components/base/_header.html
{% load static %}

<header>
    <div class="container py-2">
        <div class="row py-4 pb-0 pb-sm-4 align-items-center ">

            <div class="col-sm-4 col-lg-3 text-center text-sm-start">
                <div class="main-logo">
                    <a href="{% url 'main:home-page' %}">
                        <img src="{% static 'images/logo.png' %}" alt="logo" class="img-fluid">
                    </a>
                </div>
            </div>

            <div class="col-sm-6 offset-sm-2 offset-md-0 col-lg-5 d-none d-lg-block">
                <div class="search-bar border rounded-2 px-3 border-dark-subtle">
                    <form id="search-form" class="text-center d-flex align-items-center" action="" method="get">
                        <input type="text" class="form-control border-0 bg-transparent"
                               placeholder="Search for more than 10,000 products"/>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                            <path fill="currentColor"
                                  d="M21.71 20.29L18 16.61A9 9 0 1 0 16.61 18l3.68 3.68a1 1 0 0 0 1.42 0a1 1 0 0 0 0-1.39ZM11 18a7 7 0 1 1 7-7a7 7 0 0 1-7 7Z"/>
                        </svg>
                    </form>
                </div>
            </div>

            <div
                    class="col-sm-8 col-lg-4 d-flex justify-content-end gap-5 align-items-center mt-4 mt-sm-0 justify-content-center justify-content-sm-end">
                <div class="support-box text-end d-none d-xl-block">
                    <span class="fs-6 secondary-font text-muted">Phone</span>
                    <h5 class="mb-0">+980-34984089</h5>
                </div>
                <div class="support-box text-end d-none d-xl-block">
                    <span class="fs-6 secondary-font text-muted">Email</span>
                    <h5 class="mb-0">waggy@gmail.com</h5>
                </div>


            </div>
        </div>
    </div>

    <div class="container-fluid">
        <hr class="m-0">
    </div>

    <div class="container">
        <nav class="main-menu d-flex navbar navbar-expand-lg ">

            <div class="d-flex d-lg-none align-items-end mt-3">
                <ul class="d-flex justify-content-end list-unstyled m-0">
                    <li>
                        <a href="{% url 'accounts:home-page' %}" class="mx-3">
                            <iconify-icon icon="healthicons:person" class="fs-4"></iconify-icon>
                        </a>
                    </li>
                    <li>
                        <a href="wishlist.html" class="mx-3">
                            <iconify-icon icon="mdi:heart" class="fs-4"></iconify-icon>
                        </a>
                    </li>

                    <li>
                        <a href="#" class="mx-3" data-bs-toggle="offcanvas" data-bs-target="#offcanvasCart"
                           aria-controls="offcanvasCart">
                            <iconify-icon icon="mdi:cart" class="fs-4 position-relative"></iconify-icon>
                            <span class="position-absolute translate-middle badge rounded-circle bg-primary pt-2">
                                03
                            </span>
                        </a>
                    </li>

                    <li>
                        <a href="#" class="mx-3" data-bs-toggle="offcanvas" data-bs-target="#offcanvasSearch"
                           aria-controls="offcanvasSearch">
                            <iconify-icon icon="tabler:search" class="fs-4"></iconify-icon>
                            </span>
                        </a>
                    </li>
                </ul>

            </div>

            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
                    aria-controls="offcanvasNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"
                 aria-labelledby="offcanvasNavbarLabel">

                <div class="offcanvas-header justify-content-center">
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>

                <div class="offcanvas-body justify-content-between">
                    <select class="filter-categories border-0 mb-0 me-5">
                        <option>Shop by Category</option>
                        {% for category in categories %}
                            <option>{{ category.name }}</option>
                        {% endfor %}
                    </select>

                    <ul class="navbar-nav menu-list list-unstyled d-flex gap-md-3 mb-0">
                        <li class="nav-item">
                            <a
                                    href="{% url 'main:home-page' %}"
                                    class="nav-link {% if request.path == '/' %}active{% endif %}">
                                Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a
                                    href="{% url 'categories:shop-page' %}"
                                    class="nav-link {% if request.path == '/categories/' %}active{% endif %}">
                                Shop
                            </a>
                        </li>
                        <li class="nav-item">
                            <a
                                    href="{% url 'blog:home-page' %}"
                                    class="nav-link {% if request.path == '/blog/' %}active{% endif %}">
                                Blog
                            </a>
                        </li>
                        <li class="nav-item">
                            <a
                                    href="{% url 'main:contact-page' %}"
                                    class="nav-link {% if request.path == '/contacts/' %}active{% endif %}">Contact</a>
                        </li>
                    </ul>

                    <div class="d-none d-lg-flex align-items-end">
                        <ul class="d-flex justify-content-end list-unstyled m-0">
                            <li>
                                <a href="{% url 'accounts:home-page' %}" class="mx-3">
                                    <iconify-icon icon="healthicons:person" class="fs-4"></iconify-icon>
                                </a>
                            </li>
                            <li>
                                <a href="wishlist.html" class="mx-3">
                                    <iconify-icon icon="mdi:heart" class="fs-4"></iconify-icon>
                                </a>
                            </li>

                            <li class="">
                                <a href="#" class="mx-3" data-bs-toggle="offcanvas" data-bs-target="#offcanvasCart"
                                   aria-controls="offcanvasCart">
                                    <iconify-icon icon="mdi:cart" class="fs-4 position-relative"></iconify-icon>
                                    <span
                                            class="position-absolute translate-middle badge rounded-circle bg-primary pt-2">
                                        03
                                    </span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</header>

core/templates/components/base/_meta.html
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="format-detection" content="telephone=no">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="author" content="">
<meta name="keywords" content="">
<meta name="description" content="">

core/templates/components/base/_scripts.html
{% load static %}

<script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
<script src="{% static 'js/swiper.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/iconify.js' %}"></script>

core/templates/components/base/_styles.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/swiper.css' %}" />
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />

<link rel="stylesheet" type="text/css" href="{% static 'css/vendor.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Chilanka&family=Montserrat:wght@300;400;500&display=swap"
  rel="stylesheet">